### ISSUE TITLE
1541 Drive Sound Emulation on BMC 64 Lite (Pi Zero)

### ISSUE THREAD

**Issue by CemTezcan** [randyrossi/bmc64#101]
Hello, 
With the 3.4 update, surprisingly, drive sound emulation on BMC lite version was available! But after the minor update about #100 issue on version 3.4, it has dissappeared as alweays is. 

Is there a way to have it back, or is it purposely disabled for the lite version from the start?

**Comment by randyrossi** [comment]
Yah, that was a mistake.  I forget sometimes my local compile has missing flags and it got into a build.

I just don't give the pi0 much attention 'cause I never intended to support it.  I might give this another check because I found a routine that was wasting some CPU each frame and that may have been why I took this out in the first place.  I'll do a performance test and enable this if it looks okay.

**Comment by CemTezcan** [comment]
Please consider at least an enable disable button if it doesn't affect performance when on "disabled" state. 

I must say Pi zero is also a great platform for bmc 64 lite which I use more often then the standard pi 3B+ for even play reflex games like Green Beret. I spotted no problem on performance so far. It's really great alternative. Thanks so much for this lite version.
