### ISSUE TITLE
real c64 breadbin keyboard connected via USB arduino not recognized.

### ISSUE THREAD

**Issue by theshinyknight** [randyrossi/bmc64#154]
Not sure what do I have to do to make it work; but it seems that BMC64 does not see it at all. The keyboard is connected to an arduino micro-controller, which is set to be recognized as keyboard. It works fine both under windows and under linux on a raspberry pi. 

But when I plug it in and boot the C64, no life sign. A regular wireless keyboard works fine, so there is something about the real keyboard that BMC does not like.

**Comment by mcgurk** [comment]
Dont use Arduino IDE and default libraries. Problem is that they create USB-device with multiple different roles. Using Arduino IDE micro is detected as serial port USB device. You can use Atmel studio to create device which acts only as keyboard.
But you don't have to do any coding yourself, because there is ready made firmware for that. soarer's keyboard controller.
https://github.com/mcgurk/Arduino-USB-HID-RetroJoystickAdapter/tree/master/C64_keyboard

**Comment by theshinyknight** [comment]
Awesome, will check that out!

The flashing was done on a teensy micro; I assume the keyboard controller linked is able to work on the teensy too? Cheers
