### ISSUE TITLE
No way to exit the emulator and boot in the terminal

### ISSUE THREAD

**Issue by theshinyknight** [randyrossi/bmc64#156]
Not sure if this is described somewhere else but I can't find a way to exit the emulator, into the terminal.

The SD card after burning it seems to not be expanded, so most of the space is not used. Also it is not possible to access any other facility related to the underlying OS; which makes hard to customize anything.

**Comment by randyrossi** [comment]
There is no terminal.  This is a bare metal program.  It does not run on top of an operating system (like Linux).  You can't escape because there is nothing to escape to.  This project is meant for dedicated C64 replicas where the Rpi is dedicated to emulating only a C64.  There are ways to share an sd card with other OS's but I don't offer tech support.  There is some info in the README.

**Comment by theshinyknight** [comment]
Thanks, I assumed that by bare metal you mean running the linux kernel and then enable vice

**Comment by lroby74** [comment]
Don't use .IMG file but .ZIP file, unzipping his contents in a FAT32 formatted partition
