### ISSUE TITLE
Disk data commit?

### ISSUE THREAD

**Issue by x48x4b** [randyrossi/bmc64#283]
Hello there,

According to my experience with BMC64 you have to detach a disk after write and before shutdown.
Otherwise the data will be lost.

Question: Is there another way to commit data to a disk?

("ordinary" Vice behaves differently.)

Best regards

**Comment by Kugelblitz360** [comment]
You can set any of the configurable Hot-Keys to a "Flush Disc" function that was implemented back in 2021.
https://github.com/randyrossi/bmc64/commit/2f029a9bba2e65e617d3614df7b41dfdacafd265
The way BMC64 is designed is that it NEVER writes to the SD card unless you specifically ask for it so that basically you can just "switch off" at any time because it is HIGHLY unlikely that you switch off during a write (you could but you'd have to be VERY fast and do it intentionally). So "Flushes" are necessary for Cartridge (Easyflash) and D64 image saves.

**Comment by x48x4b** [comment]
Thanks a lot. Works perfect!
