### ISSUE TITLE
[FR] Other key combinations for more shortcuts (C= + Shift + Fx)

### ISSUE THREAD

**Issue by lroby74** [randyrossi/bmc64#47]
I would like that you can add C= + SHIFT or C= + CTRL Key for other shortcuts too

i would like to assign "OPEN TAP FILE" , "OPEN CRT FILE", "OPEN AUTOSTART PRG/D64 FILE" menús  on other shortcuts too, so i can choose a game to load directly from keyboard without opening it from C= + F7 and browsing on correct voice in the global menú each time

**Comment by Larswad** [comment]
Just to give my own 5c's on this one. Before Randy released the 1.7 version I coded my own version of these shortcuts F1-F7. In my version I put in HardReset as one of the mapping alternatives (I really miss that one now, even if I'm staying of course on Randy's official one that is much better).
(Sidenote: Please please can we get reset as one of the mapping options as well).

However, as I use the Final Cartridge III together with the emulator and keyrah, I notice that holding the Run-Stop key down to bypass the desktop won't work, it was the same in my version. I am not sure why this is, but maybe there is some delay or upstroke that has to be done so that the emulator catches the downstate of the run-stop.

Otherwise, I think that the idea to map a "shifted" version using CTRL is absolutely great.

Thanks.

**Comment by lroby74** [comment]
i know that C= key is need for bypass desktop of FC3 or other cartridges for a clean C64 boot, like on C128 same key boots up C64 instead C128

**Comment by randyrossi** [comment]
Reset will be in the next release.  I held back because I wanted to add an optional confirmation dialog before the reset took effect.  I want to give people an option to avoid accidental reset especially with the gamepad buttons that are easy to hit.  I'll try to get the Run-Stop key to work with reset too.  It seems to work with VICE on the desktop okay.

**Comment by lroby74** [comment]
Other 4 shortcut keys added (CTRL + F1/3/5/7, thank you! I can close this ticket
